version: '2'
services:
  app:
    build: .
    working_dir: /app/src
    volumes: 
      - ./src:/app/src
      - /app/src/node_modules
    ports:
      - 3000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true